ethiopian_medical:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_native }}"
      user: "{{ env_var('POSTGRES_USER', 'medical_user') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'secure_password_123') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'ethiopian_medical_db') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      search_path: public
      role: null
      sslmode: prefer
      connect_timeout: 10
      retries: 3

    staging:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_native }}"
      user: "{{ env_var('POSTGRES_USER', 'medical_user') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'secure_password_123') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'ethiopian_medical_db') }}"
      schema: staging
      threads: 4
      keepalives_idle: 0
      search_path: staging
      role: null
      sslmode: prefer
      connect_timeout: 10
      retries: 3

    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_native }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 8
      keepalives_idle: 0
      search_path: public
      role: null
      sslmode: require
      connect_timeout: 30
      retries: 5

    test:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_native }}"
      user: "{{ env_var('POSTGRES_USER', 'medical_user') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD', 'secure_password_123') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'ethiopian_medical_db') }}"
      schema: test
      threads: 2
      keepalives_idle: 0
      search_path: test
      role: null
      sslmode: prefer
      connect_timeout: 10
      retries: 1
